name: Build and Deploy Elevplan to Azure

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build and publish app
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # 1. Byg Blazor og læg det over i wwwroot
      - name: Publish Blazor WebAssembly
        run: dotnet publish ./ComwellElevplan/ComwellElevplan.csproj -c Release -o ../ServerApi/wwwroot

      # 2. Byg og udgiv ServerApi
      - name: Publish Server API
        run: dotnet publish ./ServerApi/ServerApi.csproj -c Release -o ./publish

      - name: Upload artifact for deploy
        uses: actions/upload-artifact@v4
        with:
          name: elevplan-app
          path: ./publish

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: elevplan-app
          path: ./publish

      # 3. Login til Azure med Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5578503AB0A74745945D87DE175D16E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94541A90CBE2472A9CBB10181A4FB5A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_66E59D19EAD64930BE01CACC487E1CA4 }}
          auth-type: SERVICE_PRINCIPAL

      # 4. Deploy til Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Elevplan'
          package: ./publish
